#!/system/bin/sh

#mount system rw
sh /system/bin/siam_rw.sh
	
#apps to delete

for i in CarHomeLauncher Androidian CarHomeGoogle Cyanbread Protips ;
do
	if [ -e /system/app/$i.apk ];
	then
		rm -f /system/app/$i.apk;
		un=$(pm list packages -f | grep $i.apk | sed 's/\(.*=\)\(.*\)/\2/');
		pm uninstall $un;
	fi;
done;

#mount system ro
sh /system/bin/siam_ro.sh